# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &kuper age1xy2hazxyct73cpeft4vgslq8qat9amytejjqwxcazc7ve92t09fq79zq5q
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *kuper
